VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 0
VERSION_SUFFIX = 'alpha1'

VERSION = '%d.%d.%s%s' % (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, '-%s' % VERSION_SUFFIX if VERSION_SUFFIX else '')
