VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 4
VERSION_SUFFIX = ''

VERSION = '%d.%d.%s%s' % (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, '-%s' % VERSION_SUFFIX if VERSION_SUFFIX else '')


__all__ = [
    'VERSION_MAJOR',
    'VERSION_MINOR',
    'VERSION_PATCH',
    'VERSION_SUFFIX',
    'VERSION',
]
