name: Post pull request comment

on:
  workflow_run:
    workflows: [Test suite]
    types: [completed]

jobs:
  post_pr_comment:
    uses: BMCV/github-workflows/.github/workflows/coverage-post-pr-comment.yml@feaa032b63125d343bd0fbee1d7e23b27e7894e3
